import json, os
from datetime import datetime

STORE_PATH = "metadata/approved_docs.json"

def _load() -> dict:
    os.makedirs("metadata", exist_ok=True)
    if not os.path.exists(STORE_PATH):
        return {}
    with open(STORE_PATH) as f:
        return json.load(f)

def _save(data: dict):
    with open(STORE_PATH, "w") as f:
        json.dump(data, f, indent=2, default=str)

def save_doc(table: str, doc: dict, model: str):
    store = _load()
    store[table] = {
        **doc,
        "_meta": {
            "approved_at": datetime.now().isoformat(),
            "generated_by": model,
            "version": store.get(table, {}).get(
                "_meta", {}).get("version", 0) + 1
        }
    }
    _save(store)

def get_doc(table: str) -> dict | None:
    return _load().get(table)

def get_all_docs() -> dict:
    return _load()

def export_markdown(table: str) -> str:
    doc = get_doc(table)
    if not doc:
        return f"No approved documentation for {table}"
    md = f"# Table: `{table}`\n\n"
    md += f"{doc.get('table_description','')}\n\n"
    md += "## Columns\n\n"
    md += "| Column | Description | Example |\n"
    md += "|--------|-------------|----------|\n"
    for col in doc.get("columns", []):
        md += f"| `{col['name']}` | {col['description']} | {col.get('example_value','')} |\n"
    md += "\n## Business Glossary\n\n"
    for g in doc.get("business_glossary", []):
        md += f"**{g['term']}**: {g['definition']}\n\n"
    md += f"\n*Generated by {doc['_meta']['generated_by']} · "
    md += f"Approved {doc['_meta']['approved_at'][:10]}*\n"
    return md